In [2]:
## Data Selection in series

In [3]:
##Series as Dictionary

In [6]:
import numpy as np

In [7]:
import pandas as pd

In [61]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index= ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [57]:
'a' in data

False

In [63]:
data['b']
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [18]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [21]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [23]:
##Series as 1 day array (Numpy array)
data['a':'c'] ## slicing by explicit index

a    0.25
b    0.50
c    0.75
dtype: float64

In [25]:
data[0:2] #slicing by implicit integer index

a    0.25
b    0.50
dtype: float64

In [26]:
data[(data>0.3) & (data<0.8)] #masking

b    0.50
c    0.75
dtype: float64

In [28]:
data[['a','e']]  # fancy indexing

a    0.25
e    1.25
dtype: float64

In [30]:
data = pd.Series(['a','b','c'], index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [31]:
data[1]

'a'

In [32]:
data[1:3]

3    b
5    c
dtype: object

In [34]:
data.loc[1] # loc uses explicit indexing. It searches through rowname. 

'a'

In [35]:
data.loc[1:3] 

1    a
3    b
dtype: object

In [36]:
data.iloc[1] #iloc uses implicit indexing. It searches through rownumber. 

'b'

In [37]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [38]:
#Data Selection in DataFrame
## Data Frame as disctionary

In [64]:
area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
'Illinois': 149995})

pop = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})

data = pd.DataFrame({'area':area,'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [41]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [42]:
data.area # This is shorthand for the above but dont work always. 
#If the column names are not strings, or if the column names conflict with methods of the DataFrame

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [44]:
data.pop is data['pop'] # As DataFrame has a method named pop(). 

False

In [70]:
data['density'] = data['pop']/data['area'] # Adding new column to the DataFrame
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [50]:
#DataFrame as 2D Array
data.values # this way we can view a data frame as a 2d array.
#type(data.values) -> numpy.ndarray

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [52]:
data.T #transpose the data.
#type(data.T) # pandas.core.frame.DataFrame

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [54]:
data.values[0] #accessing rows 

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [55]:
data['area'] #accessing columns 

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [66]:
#Array like indexing
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [67]:
data.loc[:'Illinois',:'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [73]:
data.ix[:3,:'pop']

c:\users\oj268\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [71]:
data.loc[data.density>100,['pop','density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [ ]:
#Additional Indexing - Indexing refer to columns, slicing refers to rows.

In [81]:
data['Texas':'New York']
#data

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [83]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [85]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

In [86]:
## Operation on data in Pandas. 

In [87]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [88]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [89]:
#There are some ufunc which preserves the index ordering 
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [90]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [91]:
#For binary operations on two Series or DataFrame objects, Pandas will align indices
#in the process of performing the operation.
#Index alignment in Series

In [92]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127}, name='population')

In [93]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [94]:
area.index | population.index # the index is the union of the 2 series

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [95]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [96]:
A.add(B, fill_value=0) #add() is same as the above, here default value can be set for NaN

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [101]:
#Index Alignment in DataFrame
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
columns=list('AB'))
A

A   B
0   8   1
1  19  14

In [100]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
columns=list('BAC'))
B

B  A  C
0  6  4  8
1  6  1  3
2  8  1  9

In [102]:
A+B

A     B   C
0  12.0   7.0 NaN
1  20.0  20.0 NaN
2   NaN   NaN NaN

In [108]:
fill = A.stack().mean()
A.add(B,fill_value=fill)

A     B     C
0  12.0   7.0  18.5
1  20.0  20.0  13.5
2  11.5  18.5  19.5

In [109]:
#Operation between DataFrame and Series
A = rng.randint(10, size=(3, 4)) # A 2d arra
A

array([[6, 7, 2, 0],
       [3, 1, 7, 3],
       [1, 5, 5, 9]])

In [110]:
A-A[0] #Rowise substraction takes place a 2D and 1d array as in numpy

array([[ 0,  0,  0,  0],
       [-3, -6,  5,  3],
       [-5, -2,  3,  9]])

In [113]:
df=pd.DataFrame(A,columns=list('PQST'))
df

P  Q  S  T
0  6  7  2  0
1  3  1  7  3
2  1  5  5  9

In [114]:
df-df.loc[0] # diff between dataframe and a series same as above(rowise)

P  Q  S  T
0  0  0  0  0
1 -3 -6  5  3
2 -5 -2  3  9

In [124]:
df.sub(df['Q'], axis=0)# column wise subtraction

P  Q  S  T
0 -1  0 -5 -7
1  2  0  6  2
2 -4  0  0  4